### ISSUE TITLE
Feature: plugin commands

### ISSUE THREAD

**Issue by distantnative** [getkirby-v2/cli#6]
```
kirby plugin:install distantnative/multiselect
kirby plugin:update distantnative/multiselect
kirby plugin:delete distantnative/multiselect
```

Would be great to also have a command to update all installed plugins `kirby plugin:update --all`?

**Comment by JonasDoebertin** [comment]
I'd love to have a `kirby plugin:update --all` command available, too.

Also, how about a flag to control the branch that get's installed? Sometimes you explicitely want to add a dev version of a plugin. somthing like this could come in handy: `kirby plugin:install distantnative/multiselect --branch develop`?

I guess this could be introduced at a later date, though.

**Comment by runxel** [comment]
I would like to see all the plugins I have installed. Maybe even with the according version number.

**Comment by maxxst** [comment]
for me that sound like we need a `kirby.yml` or something like that to save all that dependencies something like bower but for the kirby CLI

```yml
name: MyAwesomeProject
type: Site|Plugin|Fieldtype ...
dependencies:
  plugins:
    - plugin_a:
       name: foo
       version: 0.2
       url: github.com/foo/bar
```
